### ISSUE TITLE
authentication required

### ISSUE THREAD

**Issue by sergiofteixeira** [nlewo/comin#57]
```
exporter:
  listen_address: ''
  port: 4243
flake_subdirectory: .
hostname: monitoring
remotes:
- auth:
    access_token_path: /tmp/token
  branches:
    main:
      name: main
    testing:
      name: testing-monitoring
  name: origin
  poller:
    period: 60
  timeout: 300
  url: https://github.com/blabla/nix.git
state_dir: /var/lib/comin

```
this is my current config generated by nix, and i get Pull from remote 'origin' failed: authentication required, but i can manually use this token to clone the repo..
any clue?
